# Generated by Django 4.2.5 on 2023-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('sentiment', models.CharField(max_length=255)),
            ],
        ),
    ]
